baseURL = "https://osmancakir.io"
languageCode = "en-us"
title = "osman cakir"
theme = "berbera"


pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
contentDir="content"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS"]
  section = ["RSS"]